[package]
name = "s3etag"
version = "0.1.0"
authors = ["LiosK <contact@mail.liosk.net>"]
license = "Apache-2.0"
edition = "2021"
description = "Compute AWS S3 Etags"
repository = "https://github.com/LiosK/s3etag-rs"
publish = false

[dependencies]
clap = "4.5"
md-5 = "0.10"
memmap2 = "0.9"

[profile.release]
lto = true
